CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT PK_USER PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS purchases
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             VARCHAR(2500)                           NOT NULL,
    status_purchases VARCHAR(500)                            NOT NULL,
    is_consumable    BOOLEAN                                 NOT NULL,
    buyer_id         BIGINT,
    dimension        VARCHAR(500),
    quantity         BIGINT,
    CONSTRAINT PK_PURCHASE PRIMARY KEY (id),
    CONSTRAINT FK_PURCHASE_FOR_BUYER_ID FOREIGN KEY (buyer_id) REFERENCES users (id)

);

CREATE TABLE IF NOT EXISTS events
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(512) NOT NULL,
    status_event VARCHAR(500) NOT NULL,
    participant_id BIGINT,
    purchase_id bigint,
    start_date TIMESTAMP,
    end_date TIMESTAMP,

    CONSTRAINT PK_EVENT PRIMARY KEY (id),
    CONSTRAINT FK_EVENT_FOR_PARTICIPANTS_ID FOREIGN KEY (participant_id) REFERENCES users (id),
    CONSTRAINT FK_EVENT_FOR_PURCHASE_ID FOREIGN KEY (purchase_id) REFERENCES purchases (id)
);
